### PR TITLE
feat: add ext db packages to REST Agent (#3269)

### PR DESCRIPTION
**Pull request by afrancoc2000**
Signed-off-by: Ana Maria Franco <afrancoc2000@gmail.com>

**Title:**
Adding extended database packages to the Rest Agent

**Description:**
The Rest Agent doesn't have an easy way to use the [extended package databases](https://github.com/hyperledger/aries-framework-go-ext/tree/ce8776c10037404f5c31a67aced0df6828bc4c28), so, I'm adding the posibility to use them in here.

[Issue 3269](https://github.com/hyperledger/aries-framework-go/issues/3269)

**Summary:**

I'm adding support for the Rest Agent to: couchdb, mongodb, mysql, postgresql, from the [aries-framework-go-ext](https://github.com/hyperledger/aries-framework-go-ext) package, and updating the docs.

Also I ran `go mod tidy -go=1.16 && go mod tidy -go=1.17` and updated the go.mod keeping compatibility with go 1.16. Not sure if compatibility with go 1.16 is still wanted.

### CODE REVIEW

**Review by sudeshrshetty — APPROVED** [review]

**Review by sudeshrshetty — COMMENTED** [review]
thanks for your contribution @afrancoc2000 .

Please fix the BDD test issues caused by go mod updates.

**Comment by DRK3** [comment]
Thanks for the PR @afrancoc2000! (and extra thanks for updating the docs too!) Looks good to me.

**Comment by afrancoc2000** [comment]
Thank you @sudeshrshetty and @DRK3 , I'm glad to help. Can you approve to run the workflows please? I made a change in the go.sum file and I would like to check if that fixes the problem with the BDD test.

**Comment by afrancoc2000** [comment]
Hi guys, I fixed the nolint comments, can you please approve the workflows again, to check if its fixed? Thanks!

**Comment by afrancoc2000** [comment]
Hi @sudeshrshetty @DRK3 @troyronda I did a rebase and squached the no-lint commit. Can you run the workflows again please? Thanks!

**Comment by sudeshrshetty** [comment]
@afrancoc2000 done, but still I can see some failures, Please check.

**Comment by afrancoc2000** [comment]
Hi @sudeshrshetty I fixed it, can we try again? thanks

**Comment by DRK3** [comment]
Hi @afrancoc2000, are you able to run the checks locally with `make all`?

**Comment by afrancoc2000** [comment]
@DRK3 I have a windows machine and running `make  all` gives me a lot of issues, running in windows I get path problems and in the wsl I get line endings errors, so I prefer running the actions on github, it's more straightforward. I'm going to try with a devcontainer though maybe that way make will work whithout issues

**Comment by DRK3** [comment]
Hi @afrancoc2000, yeah I believe the scripts only work on Linux and Mac. I tried running through `make all` on my Mac using your branch and it worked fine for me, so perhaps the CI was just really slow when you tested. @sudeshrshetty, can you get them to run again?

**Comment by DRK3** [comment]
(on a side note, if the scripts are only compatible with Linux and Mac, I could update the docs. @sudeshrshetty @rolsonquadras, do you know if they're supposed to work on Windows?)

**Review by DRK3 — APPROVED** [review]

**Pull request merged**
