### PR TITLE
Switch to using mathlib

### PR DESCRIPTION
**Pull request by ale-linux**
**Title:**
Use [mathlib](https://github.com/IBM/mathlib) as the implementation for elliptic curve operations.

**Description:**
This PR is an implementation of this [proposal](https://github.com/hyperledger/aries-framework-go/issues/3575).

**Summary:**

This PR changes the dependency used to handle the operations on elliptic curves needed by the BBS+ implementation. Instead of directly using the [kilic](https://github.com/kilic/bls12-381) implementation. we recommend switching to [mathlib](https://github.com/IBM/mathlib): mathlib is a module that exposes a common set of API backed by a number of different libraries ([amcl](https://github.com/hyperledger/fabric-amcl), [ConsenSys/gnark-crypto](https://github.com/ConsenSys/gnark-crypto) and [kilic](https://github.com/kilic/)). It currently supports the following curves: [FP256BN](https://neuromancer.sk/std/other/Fp256BN), [BN254](https://neuromancer.sk/std/bn/bn254), [BLS12_377](https://neuromancer.sk/std/bls/BLS12-377) and [BLS12_381](https://neuromancer.sk/std/bls/BLS12-381) (the latter in two different variants, standard and BBS compliant). mathlib is already being used by [fabric](https://github.com/hyperledger/fabric), the [idemix](https://github.com/IBM/idemix/) implementation used by fabric, the [fabric token sdk](https://github.com/hyperledger-labs/fabric-token-sdk) and the [fabric smart client](https://github.com/hyperledger-labs/fabric-smart-client).

### CODE REVIEW

**Comment by ale-linux** [comment]
@sudeshrshetty : as discussed last week, here's the PR and here's the associated [proposal](https://github.com/hyperledger/aries-framework-go/issues/3575).

**Comment by adecaro** [comment]
Hi @sudeshrshetty , we would really appreciate your feedback on the PR. We think it can bring good value to the project overall. Please, let us know :)

**Review by sudeshrshetty — APPROVED** [review]

**Comment by sudeshrshetty** [comment]
@DRK3 @fqutishat @Moopli please review this PR and provide your feedback. Let us know if it is going to impact anything we have implemented in [TrustBloc](https://github.com/trustbloc).

**Review by DRK3 — APPROVED** [review]
Looks good to me, I would suggest having @Moopli take a look before merging :)

**Review by Moopli — APPROVED** [review]

**Comment by sudeshrshetty** [comment]
@ale-linux can you please squash your commits & re-push 
https://github.com/hyperledger/aries-framework-go/blob/main/.github/CONTRIBUTING.md#pull-request

**Comment by ale-linux** [comment]
Done - all tests run successfully on my node - unclear why they fail.. maybe a flaky test?

**Comment by ale-linux** [comment]
Any news?

**Comment by DRK3** [comment]
@sudeshrshetty I think @ale-linux is right, it's a flaky test issue. @Moopli is probably a bit more familiar with the tests, do you recognize those failures? If it's an ongoing flaky test issue, I think this PR is good to merge :)

**Comment by ale-linux** [comment]
@sudeshrshetty: I'm happy to discuss any further open points/necessary changes, but if you think it is ready, would you mind merging? Otherwise I need to keep rebasing/fixing conflicts with upstream...

**Comment by ale-linux** [comment]
...and the flaky test also passed, I think it's a sign that it's time to merge :wink:

**Comment by ale-linux** [comment]
another rebase and now the flakes strike again... :cry:

**Comment by sudeshrshetty** [comment]
Sorry, I am re-triggering these failed tests to make succeed CI, so that I can merge it.

**Comment by ale-linux** [comment]
@sudeshrshetty : All tests have passed now - thx!

**Comment by ale-linux** [comment]
Could we please merge now gents? @sudeshrshetty @fqutishat

**Pull request merged**
