### PR TITLE
externalize agent parameters + router

### PR DESCRIPTION
**Pull request by cnuss**
**Title:**
Allow External Usage of `agentParameters` and `mux.Router`

**Description:**
To allow for another server framework than golang's `http`, we need to externalize the creation of `mux.NewRouter()`.

**Summary:**
Related: #3224 

When @borancar and I first authored #3224, we copied and pasted `start.go` and named it `aires.go` to gain access to `mux.NewRouter()`, so we could plug it into another server framework, as Lambda does not use golang's `http` package, however it is compatible with gorillamux.

So this PR allows us to import `startcmd` and leverage a couple new functions:
 - `NewAgentParameters()`
    - `AgentParameters` is now an exported type
    - `AgentParameters` has a new method: `NewRouter()`
 - nil-safety on helper functions for `cobra.Command`
   - Our lambda integration will use environment variables exclusively, so we pass `nil` when constructing `AgentParameters`

### CODE REVIEW

**Comment by cnuss** [comment]
FYI @troyronda @rolsonquadras @borancar this is released to #3224 to remove the copied/pasted aries.go we added

**Review by sudeshrshetty — APPROVED** [review]

**Review by rolsonquadras — APPROVED** [review]

**Review by fqutishat — APPROVED** [review]

**Comment by cnuss** [comment]
@rolsonquadras I fixed some linting issues can you allow the workflows to run?

**Comment by cnuss** [comment]
@rolsonquadras sorry for the back and fourth, i enabled GH Actions on my Fork to get all the other Unit Test/Linting issues resolved.

We should be good to go now if you can run workflows once again!

**Comment by troyronda** [comment]
@cnuss It looks like the branch is out-of-date with the base branch.

**Comment by cnuss** [comment]
@troyronda thank you, i just sync'd with main!

could you trigger GH Actions again?

also added a unit test to get hopefully get codecov in order 🙏 

cc: @sudeshrshetty @fqutishat

**Comment by cnuss** [comment]
@troyronda @sudeshrshetty @fqutishat these linting issues, first time collaborator pauses, and codecov breakages are really frustrating, and the only way i can figure out i've done something wrong is by committing then waiting

could one of you you attempt to push this PR over the finish line? i'm now having an unrelated unit test failure, probably because i'm using os.Setenv (appartently i can't use t.Setenv because we're on an older version of go?)

i've given each of you maintainer access to https://github.com/scaffoldly/aries-framework-go

**Pull request merged**
