### PR TITLE
Add GetDIDExchangeController in AriesController interface

### PR DESCRIPTION
**Pull request by cyrilhl**
**Title:**
Add GetDIDExchangeController in AriesController interface

**Description:**
Update api.go and add GetDIDExchangeController function

### CODE REVIEW

**Comment by troyronda** [comment]
@cyrilhl thanks for your contribution. could you please squash your commits?

FYI: the linter failed due to:
`pkg/api/api.go:20: File is not `goimports`-ed with -local github.com/hyperledger/aries-framework-go (goimports)`

**Comment by ToJen** [comment]
Thanks for this PR @cyrilhl 

To squash commits, could you try [this stackoverflow thread](https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed).

**Comment by ToJen** [comment]
Additionally @cyrilhl , you can signoff commits with the `-s` flag.

**Comment by cyrilhl** [comment]
Sorry I am doing my first time pull request and I am not very clear what I should do.
I see all checks have passed now. Do I still need signoff again ?

i had run  
"git rebase HEAD~3 --signoff" 
and 
"git push --force-with-lease origin master"
15 minutes ago

based on the guideline in DCO checking

**Comment by ToJen** [comment]
Not anymore since the DCO checks were successful. My comment was made before the last push. 

Once you squash the commits, we'll be ready to merge this

**Comment by ToJen** [comment]
Hello @cyrilhl are you able to squash the commits into 1? We would like to merge your contribution.

**Comment by cyrilhl** [comment]
Sorry, It seems I messing up the things or should I close this request and start over again with only one commit

**Comment by ToJen** [comment]
Yes you can make a new one if it works better for you. 
For future reference, here's how to amend commits:
1. make changes on a new branch
2. push that branch
3. make a PR from that feature branch (not the main branch)
4. then, to modify the PR without increasing the num of commits:
a] `git commit --amend --no-edit -S`
b] `git push -f <your_remote> <branch_name>`

this will ensure there's only one commit on the PR

**Comment by cyrilhl** [comment]
Thank you very much for your help, I start over again.

**Pull request closed without merging**
