### PR TITLE
refactor: Storage interface update to support encrypted data

### PR DESCRIPTION
**Pull request by rolsonquadras**
Refactor storage interface based on conversion in #26 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

**Comment by llorllale** [comment]
@rolsonquadras 

> based on conversion in #22

You mean #26

**Comment by rolsonquadras** [comment]
> @rolsonquadras
> 
> > based on conversion in #22
> 
> You mean #26

Yes @llorllale. Updated the PR comment.

**Comment by troyronda** [comment]
I'm wondering about the end-state of the deleted interfaces. Are they going to be used later as a middle layer?

**Comment by rolsonquadras** [comment]
> I'm wondering about the end-state of the deleted interfaces. Are they going to be used later as a middle layer?

@troyronda I feel we can delete now and restore later based on use case. (those were just interfaces, also later we might have more clarity on the use cases when we explore each feature). For now, we can focus just on Storage.

**Pull request merged**
