### PR TITLE
Fix various javascript vulns

### PR DESCRIPTION
**Pull request by dhh1128**
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>

Github Dependabot reports numerous vulnerabilities in the minor javascript codebases (test, worker) within this framework. Some of the vulns are more serious than others.

I ran `npm audit fix` to see if all the problems could be fixed automatically. Answer = no. At least two or three packages (karma, mocha) required a major version update (so, potentially breaking) to get rid of a vuln. I then ran `npm audit fix --force` to generate a new, clean version of dependencies, including those breaking changes. I don't have familiarity with how CI works with this codebase, so I'm not sure how to evaluate whether I broke anything.

Suggestion: let CI tell you if I broke anything. If no, merge. If yes, either have a javascript expert fix the tangled dependency vulns, or push back to me and teach me how to do CI, and I'll attempt it when I get around to it.

### CODE REVIEW

**Review by soluchok — APPROVED** [review]

**Comment by rolsonquadras** [comment]
@dhh1128 
> Suggestion: let CI tell you if I broke anything. If no, merge. If yes, either have a javascript expert fix the tangled dependency vulns, or push back to me and teach me how to do CI, and I'll attempt it when I get around to it.

The [BDD tests](https://github.com/hyperledger/aries-framework-go/pull/2324/checks?check_run_id=1415602638) that is using the aries-js-worker has passed. So, we should be good to merge.

**Review by rolsonquadras — APPROVED** [review]

**Comment by troyronda** [comment]
@dhh1128 Thanks Daniel - do you mind updating your PR title?

**Comment by dhh1128** [comment]
I updated the PR title. Now that tests have passed, I'm okay to merge if you are.

**Review by llorllale — APPROVED** [review]

**Comment by llorllale** [comment]
Thank you @dhh1128 .

Can you please squash your commits?

**Comment by dhh1128** [comment]
@llorllale : I would be happy to try, but I'm not sure how. The normal workflow for squashing commits that I know, for a submitter, is to use `git rebase -i HEAD~n`, and then to say "squash" for anything that's not substantive. But when I do that, Git doesn't show me the merge commits that deserve to be squashed; it only shows the one substantive commit, 78ef8c5a, that is the real substance of the PR:

```
...
pick 6b2a82b2 fix: Remove incorrect EDV REST client delete document status code check
pick a05fd029 ci: Fixes publish job
pick 42d35aca feat: add HeadersOpt optional function to remoteKMS New()
pick 78ef8c5a Fix various javascript vulns
pick c1ea96b9 fix: EDV REST provider store indexed attribute creation
pick 001944e7 test: BSS+ signature suite interop tests (with Mattr)
...
```

Do you have any advice for me? Or can you just squash as you merge?

**Pull request merged**
