### PR TITLE
fix: Bump kilic/bls12-381 for 32-bit arch support

### PR DESCRIPTION
**Pull request by youngjoon-lee**
**Title:**
Bump [kilic/bls12-381](https://github.com/kilic/bls12-381) for 32-bit arch support

**Description:**
Fixes https://github.com/hyperledger/aries-framework-go/issues/2758

**Summary:**
I've found that the kilic/bls12-381 panics on 32-bit architecture (the Aries local agent on Android 32-bit).
So, I fixed it: https://github.com/kilic/bls12-381/pull/31.
I'm opening a PR to use the latest kilic/bls12-381 that contains my fix.

### CODE REVIEW

**Comment by troyronda** [comment]
FYI - some of the kilic files had to be forked here: https://github.com/hyperledger/aries-framework-go/tree/main/pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381

The README in that directory provides an explanation. We should also update those forked files to be based on the same version as is set in go.mod.

**Comment by youngjoon-lee** [comment]
@troyronda I've tried to update files in the [pkg/primitive/bbs12381g2pub/internal/kilic/bls12-381](https://github.com/hyperledger/aries-framework-go/tree/main/pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381), but it wasn't simple because there have been so many changes in the bls12-381 upstream repo.
For me, it wasn't easy to understand what have been changed in the forked bls12-381 in this repo.

Could you jump into this issue and make a new forked version? IMHO, it would be simpler if you just fork the bls12-381 repo instead of copying files into `internal/bilic/bls12-381`, but I'm probably missing something that has already been discussed by you guys.

**Comment by troyronda** [comment]
@youngjoon-lee https://github.com/hyperledger/aries-framework-go/pull/2875 has updated the go.mod dependency to the latest. I am also looking at updating the forked code.

**Comment by troyronda** [comment]
@youngjoon-lee forked code updated in #2874

**Pull request closed without merging**
