### PR TITLE
mediator - message pick up integration

### PR DESCRIPTION
**Pull request by m00sey**
**Title:**
mediator - message pick up integration

Summary:

We are attempting to integrate the message pick up and mediator services. So that when configured, the message pickup service can receive forward messages, from the mediator service and store them.

In our internal implementation of router/mediation, we used the `RegisterActionEvent` mechanism to register a channel and have the messages sent over to the message pickup service. This has been superseded by the use of `RegisterActionEvent` to allow businesses logic to be run during the RequestMessage flow during mediation.

We are looking for input on how best to proceed.

### CODE REVIEW

**Comment by m00sey** [comment]
@llorllale You specifically asked about this integration before - https://github.com/hyperledger/aries-framework-go/issues/811#issuecomment-653557902 - would love to get your thoughts.

**Comment by llorllale** [comment]
@m00sey 

> @llorllale You specifically asked about this integration before - [#811 (comment)](https://github.com/hyperledger/aries-framework-go/issues/811#issuecomment-653557902) - would love to get your thoughts.

If it were me, I'd invert the dependency relation such that the `mediator` service looks up a handle to the `messagepickup` service and adds messages to it if `s.outbound.Forward()` fails.

**Comment by m00sey** [comment]
I see where you are coming from. I really like relying on `Forward` to fail and if configured, pushing them to the inbox. Thank you.

**Comment by m00sey** [comment]
@llorllale sorry for the delay, here is an implementation based off your suggestion.

**Comment by llorllale** [comment]
@m00sey thanks!

**Pull request merged**
